#!/bin/sh

# Create the vol and fa meshes
blockMesh
makeFaMesh

# create the initial dune geometry
python createGeometry.py

# create the initial time folder
cp -r 0_org 0

# Mapping fields from 2D case
cp -r 0 9
mapFields ../duneMigration -sourceTime 10
cp -r 0_org/pointDisplacement 9/

# decompose case for parrallel computing
topoSet
decomposePar

# Run sedExnerFoam
#sedExnerFoam > log
