#!/bin/sh

# Create the vol and fa meshes
blockMesh
makeFaMesh
#print ('have you changed the file format from ascii to binary in system/controlDict')

# create the initial dune geometry
python createGeometry.py

# create the initial time folder
cp -r 0_org 0



# Run sedExnerFoam
sedExnerFoam > log
